### ISSUE TITLE
Updating README Required: CodeBuild now has native integration with GitHub PRs

### ISSUE THREAD

**Issue by e271828-** [toricls/github-codebuild-integration#13]
Hi, I assume you saw this:

https://aws.amazon.com/about-aws/whats-new/2017/09/aws-codebuild-now-supports-building-github-pull-requests/

It correctly sends status back to GitHub, so I don't think this project is required anymore.

**Comment by toricls** [comment]
Hi, thanks for creating this issue. I was thinking in the same way as yours lol.

**Comment by toricls** [comment]
@e271828- Do you have any idea for differentiating this project from the native support of GitHub?

**Comment by e271828-** [comment]
Maybe tag/deploy support for people who want to avoid the complexity of CodePipeline? The native integration seems pretty solid, have been using it for a few weeks.

**Comment by toricls** [comment]
Right, I have to update the README doc and that's why I added a documentation label to this issue.

Supporting tag events seems a nice idea, thank you :) I'll create an another issue about that.

**Comment by ajw0100** [comment]
@e271828- 

> It correctly sends status back to GitHub

Does it? I can't seem to find any AWS docs on how to get CodeBuild to report back to the [Github Statuses API](https://developer.github.com/v3/repos/statuses/).

**Comment by ajw0100** [comment]
Ah, you're right. I had CodePipeline using Github as a source and CodeBuild using CodePipeline as a source. If you just create a solo CodeBuild project and set Github as the source, go through the Oauth process and check the Webhook checkbox then it all works. Thanks for confirming.
