### ISSUE TITLE
Update to documentation

### ISSUE THREAD

**Issue by skaki** [toricls/github-codebuild-integration#14]
I think we are going to need and env variable set before running make
export ENV_FILE_PATH=$(pwd)/env/$YOUR_PROJECT_NAME.env

 I was not able to run it on my mac until I set this one, which I figured out looking into the makefile.

**Comment by toricls** [comment]
@skaki  Thanks for sharing the problem and how you solved it. And I'm very glad to know that you tried to use my tool :)

(I think you don't have to export `ENV_FILE_PATH` variable anymore if you along with the updated documentation.)
